// Generated by firmware/tools/geometry_from_cad.sh — do not edit.
//
// Source: cad/v3/parameters_v3.scad. Re-run the script after changing the
// carousel pitch, the deck opening or the hex coupling, and the sketch's
// static_asserts will tell you if the change broke the park budget.
#pragma once

#define V3_CAROUSEL_BINS     8
#define V3_STEP_DEG          45.0000f   // car_pitch
#define V3_PARK_MARGIN_DEG   6.1988f   // park_margin, derived in the CAD
#define V3_COUPLING_PLAY_DEG 2.5827f   // hex_backlash, the loose hex fit
