#!/usr/bin/env bash
# Regenerate firmware/pill_dispenser/v3_geometry.h from cad/v3/parameters_v3.scad.
#
#   ./firmware/tools/geometry_from_cad.sh
#
# The sketch has to agree with the CAD about the compartment pitch, the park
# margin and the coupling's play. Retyping those is how they drift, so they are
# read straight out of the OpenSCAD parameters. The generated header is committed,
# so building the sketch does not need OpenSCAD — only changing the geometry does.
set -euo pipefail

cd "$(dirname "$0")"
OUT=../pill_dispenser/v3_geometry.h
SRC=../../cad/v3/parameters_v3.scad

if command -v xvfb-run >/dev/null 2>&1; then OSCAD=(xvfb-run -a openscad); else OSCAD=(openscad); fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# OpenSCAD needs an output target even though we only want the echo.
"${OSCAD[@]}" -o "$TMP/ignored.stl" dump_geometry.scad >"$TMP/log" 2>&1 || true
LINE=$(grep -o 'V3GEOM[^"]*' "$TMP/log" | head -1 || true)

if [[ -z "$LINE" ]]; then
    echo "error: no V3GEOM line from OpenSCAD. Log:" >&2
    cat "$TMP/log" >&2
    exit 1
fi

val() { sed -n "s/.*[[:space:]]$1=\([0-9.-]*\).*/\1/p" <<<"$LINE"; }
BINS=$(val bins); STEP=$(val step); MARGIN=$(val park_margin); PLAY=$(val play)

[[ -n "$BINS" && -n "$STEP" && -n "$MARGIN" && -n "$PLAY" ]] || {
    echo "error: could not parse: $LINE" >&2; exit 1; }

{
    echo "// Generated by firmware/tools/geometry_from_cad.sh — do not edit."
    echo "//"
    echo "// Source: cad/v3/parameters_v3.scad. Re-run the script after changing the"
    echo "// carousel pitch, the deck opening or the hex coupling, and the sketch's"
    echo "// static_asserts will tell you if the change broke the park budget."
    echo "#pragma once"
    echo
    printf '#define V3_CAROUSEL_BINS     %d\n' "$BINS"
    printf '#define V3_STEP_DEG          %.4ff   // car_pitch\n' "$STEP"
    printf '#define V3_PARK_MARGIN_DEG   %.4ff   // park_margin, derived in the CAD\n' "$MARGIN"
    printf '#define V3_COUPLING_PLAY_DEG %.4ff   // hex_backlash, the loose hex fit\n' "$PLAY"
} >"$OUT"

echo "wrote $(cd "$(dirname "$OUT")" && pwd)/$(basename "$OUT") from $SRC"
cat "$OUT"
